In [15]:
# 전통적 설치 방법
!pip install pandas
import pandas as pd

Collecting pandas
  Using cached pandas-3.0.3-cp314-cp314-win_amd64.whl.metadata (19 kB)
Collecting numpy>=2.3.3 (from pandas)
  Using cached numpy-2.4.6-cp314-cp314-win_amd64.whl.metadata (6.6 kB)
Collecting python-dateutil>=2.8.2 (from pandas)
  Using cached python_dateutil-2.9.0.post0-py2.py3-none-any.whl.metadata (8.4 kB)
Collecting tzdata (from pandas)
  Using cached tzdata-2026.2-py2.py3-none-any.whl.metadata (1.4 kB)
Collecting six>=1.5 (from python-dateutil>=2.8.2->pandas)
  Using cached six-1.17.0-py2.py3-none-any.whl.metadata (1.7 kB)
Using cached pandas-3.0.3-cp314-cp314-win_amd64.whl (9.9 MB)
Using cached numpy-2.4.6-cp314-cp314-win_amd64.whl (12.5 MB)
Using cached python_dateutil-2.9.0.post0-py2.py3-none-any.whl (229 kB)
Using cached six-1.17.0-py2.py3-none-any.whl (11 kB)
Using cached tzdata-2026.2-py2.py3-none-any.whl (349 kB)
Installing collected packages: tzdata, six, numpy, python-dateutil, pandas

   ---------------------------------------- 0/5 [tzdata]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ------------------------ --------------- 3/5 [python-dateutil]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   ---------------------------------------- 5/5 [pandas]

Successfully installed numpy-2.4.6 pandas-3.0.3 python-dateutil-2.9.0.post0 six-1.17.0 tzdata-2026.2

In [ ]:
# 데이터 형식
# 시리즈, 데이터프레임.
s = pd.Series([10, 20, 30])

In [19]:
s.values

array([10, 20, 30])

In [18]:
type(s.values)

numpy.ndarray

In [ ]:
# 데이터프레임 : 2차원 데이터를 다룬다.

In [21]:
df = pd.DataFrame({
    'name' : ['홍길동', '임꺽정'],
    'age' : [20, 30],
    'math' : [80, 90],
    'grade' : ['B', 'A']
})

In [22]:
df

  name  age  math grade
0  홍길동   20    80     B
1  임꺽정   30    90     A

In [23]:
df.values

array([['홍길동', 20, 80, 'B'],
       ['임꺽정', 30, 90, 'A']], dtype=object)

In [24]:
df.head(1)

  name  age  math grade
0  홍길동   20    80     B

In [25]:
df.shape

(2, 4)

In [26]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    2 non-null      str
 1   age     2 non-null      int64
 2   math    2 non-null      int64
 3   grade   2 non-null      str
dtypes: int64(2), str(2)
memory usage: 196.0 bytes

In [27]:
df.describe()

             age       math
count   2.000000   2.000000
mean   25.000000  85.000000
std     7.071068   7.071068
min    20.000000  80.000000
25%    22.500000  82.500000
50%    25.000000  85.000000
75%    27.500000  87.500000
max    30.000000  90.000000

In [28]:
df['name']

0    홍길동
1    임꺽정
Name: name, dtype: str

In [32]:
print(df['name'], type(df['name']))

0    홍길동
1    임꺽정
Name: name, dtype: str <class 'pandas.Series'>

In [ ]:
# 2개 컬럼 이상을 선택했을 때, DataFrame으로 차원이 유지된다..(컬럼이 선택된 데이터프레임)ㅠ
df[['name', 'math']]

  name  math
0  홍길동    80
1  임꺽정    90

In [1]:
TITANIC_URL = 'https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv'